default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: airdogndog_development
  host: localhost
  username: airdogndog

test:
  <<: *default
  database: airdogndog_test
  host: localhost
  username: airdogndog

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
